apiVersion: v1
kind: Pod
metadata:
  name: simple-ubuntu
spec:
  containers:
    - image: simple-ubuntu:latest
      name: simple-ubuntu
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"