apiVersion: v1
kind: Pod
metadata:
  name: simple-ubuntu
spec:
  containers:
    - image: simple-ubuntu:latest
      name: client-test
      imagePullPolicy: Never
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"